# Generated by Django 5.2.7 on 2026-01-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_booked',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(default='500001', max_length=6),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Agent Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
