# Generated by Django 5.2.7 on 2026-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_category_service_description_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
